<?php

// return [
//     'PAYMOB_API_KEY' => env('PAYMOB_API_KEY'),
//     'PAYMOB_INTEGRATION_CARD' => env('PAYMOB_INTEGRATION_CARD'),
//     'PAYMOB_INTEGRATION_WALLET' => env('PAYMOB_INTEGRATION_WALLET'),
//     'PAYMOB_IFRAME_CARD' => env('PAYMOB_IFRAME_CARD'),
//     'PAYMOB_SECRET_KEY' => env('PAYMOB_SECRET_KEY'),
// ];



return [
    'PAYMOB_API_KEY' => env('PAYMOB_API_KEY'),
    'PAYMOB_SECRET_KEY' => env('PAYMOB_SECRET_KEY'),
    'PAYMOB_INTEGRATION_CARD' => env('PAYMOB_INTEGRATION_CARD'),
    'PAYMOB_INTEGRATION_WALLET' => env('PAYMOB_INTEGRATION_WALLET'),
    'PAYMOB_IFRAME_CARD' => env('PAYMOB_IFRAME_CARD'),
];

